# Site settings
course_name: ML-Base Research Tools for Research Process
course_description: "Conducting research as a graduate student can be a time-consuming and demanding process. It requires a great deal of patience, persistence, and dedication to complete. Graduate students often face a variety of research challenges, including choosing the right topic, finding study participants, staying motivated throughout the process, and communicating complex ideas with peers and the larger scholarly community.

However, when graduate students are also juggling other responsibilities such as TAing or lecturing, the research process can become even more challenging. These additional duties can take up a significant amount of time and energy, leaving less time for research. As a result, graduate students may find it difficult to balance their research with their other responsibilities.

Machine learning-based research tools can be incredibly helpful for graduate students who are juggling multiple responsibilities. This is what we will discuss in this course"
course_semester: "Fall 2023"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ghhabib2.github.io/" # the base hostname & protocol for your site

schoolname: "McMaster University"
schoolurl: "https://mcmaster.ca"
twitter_username: ghhabib_pro

address: |
  1280 Main Street West  Hamilton, Ontario  L8S 4L8 | (905) 525-9140

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
