theme: jekyll-theme-minimal
title: Habib Ghaffari Hadigheh
description: [Habib Ghaffarai Hadigheh is a full-stack developer and ML-signal processing researher. Currently he is a Ph.D. student at McMaster University under supervion of Prof. Christopher Anand.]
